### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by DuckyyDude** [Xgames123/PrimitierModManager#1]
the mod manager fails to install on the latest version

**Comment by Xgames123** [comment]
Does it give an error and can you send a screenshot of that?
Where does it fail in the .msi or in the program?

Which version of windows are you running 10 or 11?

**Comment by DuckyyDude** [comment]
![Desktop Screenshot 2022 03 29 - 20 42 37 55](https://user-images.githubusercontent.com/99925055/160694282-5b92cc74-2e20-4d1c-a7a3-a652baa62358.png)
![Desktop Screenshot 2022 03 29 - 20 42 27 67](https://user-images.githubusercontent.com/99925055/160694289-f0d73944-6c85-4a25-a957-3f2e7d9ee2c9.png)
Im on windows 10

**Comment by Xgames123** [comment]
Is it fixed with the new version?

If not can you send a log file of the msi.
you can do that like this and than send the PrimitierModManager.log file
```msiexec /i "C://Full/Path/To/The/Msi/PrimitierModManager.msi" /L*V "PrimitierModManager.log"```

**Comment by DuckyyDude** [comment]
it still doesnt work same error as before and i cant find the logs

**Comment by Xgames123** [comment]
https://user-images.githubusercontent.com/78647417/160901703-5712a8cf-5d75-4a78-a6f6-a53f590f70a8.mp4

**Comment by DuckyyDude** [comment]
i got the log and it says === Verbose logging started: 31/03/2022  21:54:45  Build type: SHIP UNICODE 5.00.10011.00  Calling process: C:\Windows\system32\msiexec.exe ===
MSI (c) (40:EC) [21:54:45:293]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (40:EC) [21:54:45:293]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (40:34) [21:54:45:304]: Resetting cached policy values
MSI (c) (40:34) [21:54:45:304]: Machine policy value 'Debug' is 0
MSI (c) (40:34) [21:54:45:304]: ******* RunEngine:
           ******* Product: C:\Users\mason\Download/PrimitierModManager.msi
           ******* Action: 
           ******* CommandLine: **********
MSI (c) (40:34) [21:54:45:305]: Note: 1: 2203 2: C:\Users\mason\Download/PrimitierModManager.msi 3: -2147287037 
MSI (c) (40:34) [21:54:45:305]: MainEngineThread is returning 3
=== Verbose logging stopped: 31/03/2022  21:54:45 ===

**Comment by DuckyyDude** [comment]
in the properties i tried to trouble shoot and it said that it was incompatible with my pc

**Comment by Xgames123** [comment]
Are you running 64 or 32 bit window

https://user-images.githubusercontent.com/78647417/161290531-7115c7de-331a-406a-a676-9055f97889ec.mp4

**Comment by DuckyyDude** [comment]
im running 64 bit

**Comment by Xgames123** [comment]
I have found the problem. the installer can not access the downloads folder.
Hopefully one of these will fix it.
* Check if other msi's work on your pc
* Check if your antivirus is blocking the msi
* Try moving the msi to a different location and running it there
* Try run as administrator

https://user-images.githubusercontent.com/78647417/161386144-474e2503-d244-4ce0-85b7-e6bcb2a1cb96.mp4

**Comment by DuckyyDude** [comment]
still doesnt work i tried all the methods.

**Comment by Xgames123** [comment]
Sorry I can't find the cause of this issue.
I have created a manual install that you can do that doesn't require the msi.
https://github.com/Xgames123/PrimitierModManager/blob/WorkingBuild/MANUAL_INSTALL_INSTRUCTIONS.md

Let me know if you have any problems with the manual installation.

**Comment by DuckyyDude** [comment]
this worked perfectly, thanks.
